// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbaZ4WQnglAGn9OOscUyd0VnhLpgis0jI',
    appId: '1:990655658799:web:ffb6014c24e07ee875bfda',
    messagingSenderId: '990655658799',
    projectId: 'weather-application-38bd0',
    authDomain: 'weather-application-38bd0.firebaseapp.com',
    storageBucket: 'weather-application-38bd0.firebasestorage.app',
    measurementId: 'G-JKHN1SJCNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGLNERDKzUWB5qBqeel-4AqVyXKvPt_CU',
    appId: '1:990655658799:android:d12d37e5c98d86d075bfda',
    messagingSenderId: '990655658799',
    projectId: 'weather-application-38bd0',
    storageBucket: 'weather-application-38bd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg8UESsSLWMF3COm5KC5f2OMzD9TdoNiw',
    appId: '1:990655658799:ios:a348d4d384de1ac575bfda',
    messagingSenderId: '990655658799',
    projectId: 'weather-application-38bd0',
    storageBucket: 'weather-application-38bd0.firebasestorage.app',
    androidClientId: '990655658799-7idpnmkugsqd3lgfnmg94ufrfee7kb7p.apps.googleusercontent.com',
    iosClientId: '990655658799-745cssvpgbfl7c9catfqb7uasq7rfq92.apps.googleusercontent.com',
    iosBundleId: 'com.weatherapplication.weatherApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg8UESsSLWMF3COm5KC5f2OMzD9TdoNiw',
    appId: '1:990655658799:ios:a348d4d384de1ac575bfda',
    messagingSenderId: '990655658799',
    projectId: 'weather-application-38bd0',
    storageBucket: 'weather-application-38bd0.firebasestorage.app',
    androidClientId: '990655658799-7idpnmkugsqd3lgfnmg94ufrfee7kb7p.apps.googleusercontent.com',
    iosClientId: '990655658799-745cssvpgbfl7c9catfqb7uasq7rfq92.apps.googleusercontent.com',
    iosBundleId: 'com.weatherapplication.weatherApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbaZ4WQnglAGn9OOscUyd0VnhLpgis0jI',
    appId: '1:990655658799:web:f49b3fbcbc47149475bfda',
    messagingSenderId: '990655658799',
    projectId: 'weather-application-38bd0',
    authDomain: 'weather-application-38bd0.firebaseapp.com',
    storageBucket: 'weather-application-38bd0.firebasestorage.app',
    measurementId: 'G-C4PGTM27Q8',
  );

}